#------------------------------------------------------------------------------
#
#  $Id$
#
#  Copyright (C) 2006-2017  Florian Pose, Ingenieurgemeinschaft IgH
#
#  This file is part of the IgH EtherCAT Master.
#
#  The IgH EtherCAT Master is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License version 2, as
#  published by the Free Software Foundation.
#
#  The IgH EtherCAT Master is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with the IgH EtherCAT Master; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#  ---
#
#  The license mentioned above concerns the source code only. Using the
#  EtherCAT technology and brand is only permitted in compliance with the
#  industrial property and similar rights of Beckhoff Automation GmbH.
#
#  ---
#
#  vim: syntax=make
#
#------------------------------------------------------------------------------

TOPDIR := $(src)/../..

REV := $(shell if test -s $(TOPDIR)/revision; then \
		cat $(TOPDIR)/revision; \
	else \
		git -C $(TOPDIR) describe 2>/dev/null || echo "unknown"; \
	fi)

ifeq (0,1)
	obj-m += ec_igc.o

	ec_igc-objs := \
		igc_xdp-5.15-ethercat.o \
		igc_tsn-5.15-ethercat.o \
		igc_base-5.15-ethercat.o \
		igc_dump-5.15-ethercat.o \
		igc_main-5.15-ethercat.o \
		igc_ptp-5.15-ethercat.o \
		igc_diag-5.15-ethercat.o \
		igc_i225-5.15-ethercat.o \
		igc_mac-5.15-ethercat.o \
		igc_phy-5.15-ethercat.o \
		igc_ethtool-5.15-ethercat.o \
		igc_nvm-5.15-ethercat.o 

	CFLAGS_igc_main-5.15-ethercat.o = -DREV=$(REV)
endif

KBUILD_EXTRA_SYMBOLS := \
	/home/fudanrobotuser/github/igh/ethercat/$(LINUX_SYMVERS) \
	/home/fudanrobotuser/github/igh/ethercat/master/$(LINUX_SYMVERS)

#------------------------------------------------------------------------------
